const Joi = require('joi');
const clientConstants = require('../../common/clientConstants');

const stringField = Joi.string().trim().allow('').optional();
const boolField = Joi.boolean().optional();
const stringArray = Joi.array().items(Joi.string().trim()).optional();

const clientFields = {
  intakeDate: stringField,
  intakeId: stringField,
  firstName: Joi.string().trim().required(),
  lastName: Joi.string().trim().required(),
  preferredName: stringField,
  dateOfBirth: stringField,
  gender: Joi.string().valid(...clientConstants.GENDERS, '').optional(),
  maritalStatus: Joi.string().valid(...clientConstants.MARITAL_STATUSES, '').optional(),
  ssnLast4: Joi.string().pattern(/^\d{0,4}$/).allow('').optional(),
  streetAddress: stringField,
  aptSuite: stringField,
  city: stringField,
  state: stringField,
  zipCode: stringField,
  country: stringField,
  phone: stringField,
  phoneHome: stringField,
  email: Joi.string().email().allow('').optional(),
  preferredLanguage: stringField,
  ethnicity: stringField,
  race: stringField,
  emergencyContactName: stringField,
  emergencyContactRelationship: stringField,
  emergencyContactPhone: stringField,
  alternateContactName: stringField,
  alternateContactRelationship: stringField,
  alternateContactPhone: stringField,
  physicianName: stringField,
  physicianPhone: stringField,
  lastVisitDate: stringField,
  pharmacyName: stringField,
  pharmacyPhone: stringField,
  insuranceProvider: stringField,
  insuranceMemberId: stringField,
  insuranceGroupNumber: stringField,
  medicalConditions: stringField,
  primaryDiagnosis: stringField,
  allergies: stringField,
  currentMedications: stringField,
  specialDiet: stringField,
  mobility: stringField,
  livingArrangements: stringArray,
  livingArrangement: stringField,
  homeAccessibility: stringArray,
  residenceType: Joi.string().valid(...clientConstants.RESIDENCE_TYPES, '').optional(),
  assistiveDevices: stringArray,
  hasPets: boolField,
  petsDescription: stringField,
  fallHistory: boolField,
  fallHistoryDescription: stringField,
  serviceTypes: stringArray,
  mobilityAssistanceNeeded: boolField,
  mobilityAssistanceDescription: stringField,
  personalCareAssistanceNeeded: boolField,
  personalCareAssistanceDescription: stringField,
  careFrequency: Joi.string().valid(...clientConstants.CARE_FREQUENCIES, '').optional(),
  preferredDays: stringArray,
  preferredTimes: stringArray,
  careNotes: stringField,
  paymentResponsibility: Joi.string().valid(...clientConstants.PAYMENT_RESPONSIBILITIES, '').optional(),
  paymentResponsibilityOther: stringField,
  billingStreetAddress: stringField,
  billingCity: stringField,
  billingState: stringField,
  billingZip: stringField,
  paymentMethods: stringArray,
  authorizationSignature: stringField,
  authorizationDate: stringField,
  authorizationPrintedName: stringField,
  authorizationRelationship: stringField,
  intakeCompletedBy: stringField,
  intakeCompletedDate: stringField,
  assignedTo: stringField,
  admissionDate: stringField,
  carePlanStartDate: stringField,
  status: Joi.string().valid(...clientConstants.CLIENT_STATUSES).optional(),
  notes: stringField,
};

module.exports = {
  create: Joi.object(clientFields),
  update: Joi.object({
    ...clientFields,
    firstName: Joi.string().trim().optional(),
    lastName: Joi.string().trim().optional(),
  }),
};
