const Joi = require('joi');

const jobFields = {
  job_title: Joi.string().trim().max(255).required(),
  job_code: Joi.string().trim().max(255).required(),
  job_workplace: Joi.string().valid('onsite', 'hybrid', 'remote').required(),
  job_location: Joi.string().trim().max(255).required(),
  job_description: Joi.string().max(600).required(),
  job_requirements: Joi.string().max(600).required(),
  job_benefits: Joi.string().max(600).required(),
  job_department: Joi.string().trim().max(255).required(),
  job_function: Joi.string().trim().max(255).required(),
  employment_type: Joi.string().trim().max(255).required(),
  experience: Joi.string().trim().max(255).required(),
  education: Joi.string().trim().max(255).required(),
  keywords: Joi.array().items(Joi.string().trim()).min(1).required(),
  annual_salary_from: Joi.number().required(),
  annual_salary_to: Joi.number().greater(Joi.ref('annual_salary_from')).required(),
  currency: Joi.string().trim().max(10).required(),
  showOnCareerPage: Joi.boolean().optional(),
  stage_ids: Joi.array().items(Joi.string()).min(1).optional(),
  status: Joi.string().valid('Active', 'Closed', 'Draft').optional(),
};

module.exports = {
  create: Joi.object(jobFields),
  update: Joi.object({
    ...jobFields,
    job_title: Joi.string().trim().max(255).optional(),
    job_code: Joi.string().trim().max(255).optional(),
    job_workplace: Joi.string().valid('onsite', 'hybrid', 'remote').optional(),
    job_location: Joi.string().trim().max(255).optional(),
    job_description: Joi.string().max(600).optional(),
    job_requirements: Joi.string().max(600).optional(),
    job_benefits: Joi.string().max(600).optional(),
    job_department: Joi.string().trim().max(255).optional(),
    job_function: Joi.string().trim().max(255).optional(),
    employment_type: Joi.string().trim().max(255).optional(),
    experience: Joi.string().trim().max(255).optional(),
    education: Joi.string().trim().max(255).optional(),
    keywords: Joi.array().items(Joi.string().trim()).min(1).optional(),
    annual_salary_from: Joi.number().optional(),
    annual_salary_to: Joi.number().optional(),
    currency: Joi.string().trim().max(10).optional(),
  }),
  generateAi: Joi.object({
    job_title: Joi.string().allow('').optional(),
    job_code: Joi.string().allow('').optional(),
    job_workplace: Joi.string().allow('').optional(),
    job_location: Joi.string().allow('').optional(),
    job_department: Joi.string().allow('').optional(),
    job_function: Joi.string().allow('').optional(),
    employment_type: Joi.string().allow('').optional(),
    experience: Joi.string().allow('').optional(),
    education: Joi.string().allow('').optional(),
    keywords: Joi.array().items(Joi.string()).optional(),
    annual_salary_from: Joi.alternatives().try(Joi.number(), Joi.string().allow('')).optional(),
    annual_salary_to: Joi.alternatives().try(Joi.number(), Joi.string().allow('')).optional(),
    currency: Joi.string().allow('').optional(),
  }),
};
