module.exports = [
  {
    code: '1010',
    name: 'Employee Personal Action Form (EPAF) - TX',
    description: 'Employee personal information and action form for Texas',
    path: 'documents/fillable-forms/1010-Employee Personal Action Form (EPAF)-TX.pdf',
    fileName: '1010-Employee Personal Action Form (EPAF)-TX.pdf',
    mimeType: 'application/pdf',
    fileSize: 103949,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1020',
    name: 'Employment Application',
    description: 'Standard employment application form',
    path: 'documents/fillable-forms/1020-Employment Application_1123.pdf',
    fileName: '1020-Employment Application_1123.pdf',
    mimeType: 'application/pdf',
    fileSize: 201527,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1021',
    name: 'Equal Employment Opportunity Data Form',
    description: 'EEO data collection form',
    path: 'documents/fillable-forms/1021-Equal Employment Opportunity Data Form.pdf',
    fileName: '1021-Equal Employment Opportunity Data Form.pdf',
    mimeType: 'application/pdf',
    fileSize: 115753,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1050',
    name: 'Skills Checklist - Associates',
    description: 'Skills assessment checklist for associates',
    path: 'documents/fillable-forms/1050-Skills Checklist-Associates.pdf',
    fileName: '1050-Skills Checklist-Associates.pdf',
    mimeType: 'application/pdf',
    fileSize: 664121,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1060',
    name: 'Request for Reference',
    description: 'Form to request employment references',
    path: 'documents/fillable-forms/1060-Request for Reference.pdf',
    fileName: '1060-Request for Reference.pdf',
    mimeType: 'application/pdf',
    fileSize: 105843,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1070',
    name: 'Background Check Authorization - TX',
    description: 'Authorization form for background checks in Texas',
    path: 'documents/fillable-forms/1070-Background Check Authorization_TX.pdf',
    fileName: '1070-Background Check Authorization_TX.pdf',
    mimeType: 'application/pdf',
    fileSize: 112487,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1201',
    name: 'Handbook Acknowledgment - TX',
    description: 'Acknowledgement of employee handbook receipt for Texas',
    path: 'documents/fillable-forms/1201-Handbook Acknowledgment_TX.pdf',
    fileName: '1201-Handbook Acknowledgment_TX.pdf',
    mimeType: 'application/pdf',
    fileSize: 75908,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1202',
    name: 'Orientation Acknowledgements',
    description: 'Acknowledgement forms for orientation completion',
    path: 'documents/fillable-forms/1202-Orientation Acknowledgements.pdf',
    fileName: '1202-Orientation Acknowledgements.pdf',
    mimeType: 'application/pdf',
    fileSize: 102355,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1203',
    name: 'Orientation Curriculum - TX',
    description: 'Orientation curriculum acknowledgement for Texas',
    path: 'documents/fillable-forms/1203-Orientation Curriculum_TX.pdf',
    fileName: '1203-Orientation Curriculum_TX.pdf',
    mimeType: 'application/pdf',
    fileSize: 94052,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1204',
    name: 'Care Associate Availability',
    description: 'Availability schedule for care associates',
    path: 'documents/fillable-forms/1204-Care Associate Availability.pdf',
    fileName: '1204-Care Associate Availability.pdf',
    mimeType: 'application/pdf',
    fileSize: 78752,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1220',
    name: 'Abuse and Neglect Policy',
    description: 'Acknowledgement of abuse and neglect policies',
    path: 'documents/fillable-forms/1220-Abuse_Neglect Policy.pdf',
    fileName: '1220-Abuse_Neglect Policy.pdf',
    mimeType: 'application/pdf',
    fileSize: 93746,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1530',
    name: 'Care Associate Schedule Acknowledgement',
    description: 'Acknowledgement of care associate schedule',
    path: 'documents/fillable-forms/1530-Care Associate Schedule Acknowledgement.pdf',
    fileName: '1530-Care Associate Schedule Acknowledgement.pdf',
    mimeType: 'application/pdf',
    fileSize: 73648,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1600',
    name: 'Emergency Contact Information',
    description: 'Form for collecting emergency contact details',
    path: 'documents/fillable-forms/1600-Emergency Contact Information.pdf',
    fileName: '1600-Emergency Contact Information.pdf',
    mimeType: 'application/pdf',
    fileSize: 89554,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1720',
    name: 'Hepatitis B Consent-Declination',
    description: 'Hepatitis B vaccination consent or declination form',
    path: 'documents/fillable-forms/1720-Hepatitis B_Consent-Declination.pdf',
    fileName: '1720-Hepatitis B_Consent-Declination.pdf',
    mimeType: 'application/pdf',
    fileSize: 89800,
    isFillable: true,
    isActive: true,
  },
  {
    code: '1740',
    name: 'Pre-Employment Drug Consent',
    description: 'Consent form for pre-employment drug testing',
    path: 'documents/fillable-forms/1740-Pre-Employment Drug Consent-RVSD.pdf',
    fileName: '1740-Pre-Employment Drug Consent-RVSD.pdf',
    mimeType: 'application/pdf',
    fileSize: 90731,
    isFillable: true,
    isActive: true,
  },
  {
    code: '2900',
    name: 'ID Agreement',
    description: 'Identification agreement form',
    path: 'documents/fillable-forms/2900-ID Agreement.pdf',
    fileName: '2900-ID Agreement.pdf',
    mimeType: 'application/pdf',
    fileSize: 80657,
    isFillable: true,
    isActive: true,
  },
  {
    code: '4000',
    name: 'Nondisclosure and Noncompete - TX',
    description: 'Non-disclosure and non-compete agreement for Texas',
    path: 'documents/fillable-forms/4000-Nondisclosure_Noncompete_TX.pdf',
    fileName: '4000-Nondisclosure_Noncompete_TX.pdf',
    mimeType: 'application/pdf',
    fileSize: 102433,
    isFillable: true,
    isActive: true,
  },
  {
    code: 'I-9',
    name: 'I-9',
    description: 'Employment Eligibility Verification (Revised August 2023)',
    path: 'documents/fillable-forms/Revised I-9 (Aug. 2023).pdf',
    fileName: 'Revised I-9 (Aug. 2023).pdf',
    mimeType: 'application/pdf',
    fileSize: 488957,
    isFillable: true,
    isActive: true,
  },
  {
    code: 'W-4',
    name: 'W-4',
    description: "Employee's Withholding Certificate (2023)",
    path: 'documents/fillable-forms/W-4 2023.pdf',
    fileName: 'W-4 2023.pdf',
    mimeType: 'application/pdf',
    fileSize: 188715,
    isFillable: true,
    isActive: true,
  },
];
