module.exports = {
  MESSAGE: {
    SUCCESS: 'Success',
    NOT_FOUND: 'Not Found',
    DATA_SAVED: 'Data Saved Successfully',
    RECORD_CREATED: 'Record Created Successfully',
    RECORD_UPDATED: 'Record Updated Successfully',
    RECORD_DELETED: 'Record Deleted Successfully',
    LIST: 'Data Fetched Successfully',
    AUTH: {
      LOGIN_SUCCESS: 'Login Successful',
      INVALID_CREDENTIALS: 'Invalid email or password',
      UNAUTHORIZED: 'Unauthorized Access',
    },
    USER: {
      NOT_FOUND: 'User Not Found',
      EMAIL_ALREADY_IN_USE: 'Email address is already in use',
      USER_ID_TAKEN: 'User ID is already taken',
    },
    INVITATION: {
      SENT: 'Invitation Sent Successfully',
      NOT_FOUND: 'Invitation Not Found',
      EXPIRED: 'Invitation Has Expired',
      ALREADY_USED: 'Invitation Has Already Been Used',
      RESENT: 'Invitation Resent Successfully',
    },
    REGISTRATION: {
      COMPLETED: 'Registration Completed Successfully',
      PAYMENT_SUCCESS: 'Payment Processed Successfully',
    },
    HR: {
      CREATED: 'HR Account Created Successfully',
      UPDATED: 'HR Profile Updated Successfully',
      STATUS_UPDATED: 'HR Account Status Updated Successfully',
      NOT_FOUND: 'HR Staff Member Not Found',
      ALREADY_EXISTS: 'An HR staff member with this employee ID or email already exists',
    },
    HIRING_PIPELINE: {
      SAVED: 'Hiring pipeline saved successfully',
      STAGE_CREATED: 'Pipeline stage created successfully',
      STAGE_UPDATED: 'Pipeline stage updated successfully',
      STAGE_DELETED: 'Pipeline stage deleted successfully',
      REORDERED: 'Pipeline stages reordered successfully',
      STAGE_NOT_FOUND: 'Pipeline stage not found',
      STAGES_REQUIRED: 'At least one pipeline stage is required',
    },
    JOB: {
      CREATED: 'Job created successfully',
      UPDATED: 'Job updated successfully',
      DELETED: 'Job deleted successfully',
      NOT_FOUND: 'Job not found',
      CODE_EXISTS: 'A job with this code already exists',
      AI_GENERATED: 'Job content generated successfully',
      HIRING_COMPLETE: 'Hiring cycle marked complete — hired candidate added to caregiver roster',
      HIRING_ALREADY_COMPLETE: 'Hiring cycle is already complete for this job',
      HIRING_REOPENED: 'Hiring cycle reopened for this job',
      HIRING_COMPLETE_REQUIRES_HIRE: 'At least one candidate must be hired before completing the hiring cycle',
      HIRING_CYCLE_LOCKED: 'Reopen the hiring cycle before adding candidates or editing this job',
      PIPELINE_REQUIRED: 'Configure the hiring pipeline before posting a job',
    },
    CANDIDATE: {
      APPLIED: 'Candidate added to job successfully',
      ALREADY_APPLIED: 'This candidate has already been added to this job',
      APPLICATION_NOT_FOUND: 'Application not found',
      INVALID_STAGE: 'Invalid pipeline stage for this job',
      STAGE_UPDATED: 'Candidate stage updated successfully',
      HIRED: 'Candidate marked as hired',
      CAREGIVER_TRANSFERRED: 'Hired candidate transferred to caregiver roster',
      HIRED_LOCKED: 'Reopen the hiring cycle before changing hired candidate status',
      HIRE_UNDONE: 'Candidate moved back to final hiring stage',
      REJECTED: 'Candidate rejected',
      NOT_FOUND: 'Candidate not found',
      NOT_FINAL_STAGE: 'Candidate must be at the final pipeline stage to complete hiring',
      ALREADY_HIRED: 'Candidate has already been hired',
      NOT_ACTIVE: 'Only active candidates can be moved',
      NOT_HIRED: 'Only hired candidates can be moved back to the final stage',
      NO_NEXT_STAGE: 'No next stage available',
      NO_PREVIOUS_STAGE: 'No previous stage available',
      JOB_HIRE_LIMIT: 'Only one candidate can be hired for this job',
      CAREGIVER_ACCOUNT_CONFLICT: 'Email is already used by a non-caregiver account',
    },
    CANDIDATE_FORM: {
      INVALID_TOKEN: 'This form link is invalid or has been revoked',
      TOKEN_EXPIRED: 'This form link has expired',
      DOCUMENT_NOT_FOUND: 'Form not found for this stage',
      SUBMISSION_NOT_FOUND: 'Form submission not found',
      ALREADY_SUBMITTED: 'This form has already been submitted',
      REQUIRED_FIELDS: 'Please complete all required fields',
      SIGNATURE_REQUIRED: 'Signature is required',
      ACK_REQUIRED: 'Please acknowledge the form before submitting',
      SAVED: 'Draft saved',
      SUBMITTED: 'Form submitted successfully',
      EMAIL_RESENT: 'Form link email sent',
      NO_FORMS_FOR_STAGE: 'This stage has no forms configured',
      NO_FORMS_SELECTED: 'Select at least one form to send to the candidate',
      INVALID_DOCUMENT_CODES: 'One or more selected forms are not assigned to this stage',
      PDF_REQUIRED: 'Filled PDF document is required',
      USE_PDF_SUBMIT: 'This form must be submitted using the online PDF form',
      FORM_RESET: 'Form reset — candidate can fill again',
      CANNOT_RESET: 'Only submitted or in-progress forms can be reset',
    },
    INTERVIEW_FEEDBACK: {
      SAVED: 'Interview feedback saved',
      NOT_FOUND: 'Interview feedback not found',
    },
    CAREGIVER: {
      NOT_FOUND: 'Caregiver not found',
      PASSWORD_UPDATED: 'Caregiver password updated successfully',
    },
    CLIENT: {
      CREATED: 'Client created successfully',
      UPDATED: 'Client updated successfully',
      DELETED: 'Client deleted successfully',
      NOT_FOUND: 'Client not found',
      HAS_CARE_PLANS: 'Cannot delete client with existing care plans',
    },
    CARE_PLAN: {
      CREATED: 'Care plan created successfully',
      UPDATED: 'Care plan updated successfully',
      DELETED: 'Care plan deleted successfully',
      NOT_FOUND: 'Care plan not found',
      QUOTE_CREATED: 'Care plan quote generated successfully',
      QUOTE_ACCEPTED: 'Client onboarded and care plan activated',
      ALREADY_QUOTED: 'A quote already exists for this assessment',
      NOT_QUOTED: 'Generate a quote before accepting',
    },
    ASSESSMENT: {
      CREATED: 'Client assessment saved successfully',
      UPDATED: 'Client assessment updated successfully',
      DELETED: 'Client assessment deleted successfully',
      NOT_FOUND: 'Client assessment not found',
      ALREADY_ACCEPTED: 'This assessment has already been accepted',
    },
    INSURANCE_INTAKE: {
      CREATED: 'Insurance intake saved successfully',
      UPDATED: 'Insurance intake updated successfully',
      DELETED: 'Insurance intake deleted successfully',
      NOT_FOUND: 'Insurance intake not found',
    },
    EVV_ENROLLMENT: {
      UPDATED: 'EVV enrollment updated successfully',
      DELETED: 'EVV enrollment deleted successfully',
      NOT_FOUND: 'EVV enrollment not found',
      SUBMITTED: 'EVV enrollment submitted successfully',
      VERIFIED: 'EVV enrollment verified successfully',
      SYNCED: 'EVV enrollments synced from care plan',
      NOT_SUBMITTED: 'Enrollment must be submitted before verification',
      ALREADY_SUBMITTED: 'This enrollment has already been submitted',
    },
    VISIT: {
      SCHEDULE_CREATED: 'Visit schedule created successfully',
      SCHEDULE_UPDATED: 'Visit schedule updated successfully',
      SCHEDULE_DELETED: 'Visit schedule deleted successfully',
      SCHEDULE_NOT_FOUND: 'Visit schedule not found',
      NOT_FOUND: 'Visit not found',
      INVALID_RECURRENCE: 'Invalid recurrence type',
      DAYS_REQUIRED: 'Select at least one day for weekly schedules',
      EVV_NOT_VERIFIED: 'EVV enrollment must be verified before clocking in for this care plan',
      TOO_EARLY: 'Too early to clock in — wait until the grace window opens',
      TOO_LATE: 'Check-in window closed — you can only clock in within the grace period plus 1 hour after it',
      INVALID_CHECK_IN: 'This visit cannot be clocked in',
      INVALID_CHECK_OUT: 'This visit cannot be clocked out',
      ALREADY_CHECKED_OUT: 'This visit has already been ended',
      CHECKED_IN: 'Clocked in successfully',
      CHECKED_OUT: 'Clocked out successfully — pending agency approval',
      APPROVED: 'Visit approved successfully',
      REJECTED: 'Visit rejected',
      INVALID_APPROVAL: 'Only ended visits pending review can be approved or rejected',
      ALREADY_REVIEWED: 'This visit has already been reviewed',
    },
  },
};
