module.exports = {
  MESSAGE: {
    SUCCESS: 'Success',
    NOT_FOUND: 'Not Found',
    DATA_SAVED: 'Data Saved Successfully',
    RECORD_CREATED: 'Record Created Successfully',
    RECORD_UPDATED: 'Record Updated Successfully',
    RECORD_DELETED: 'Record Deleted Successfully',
    LIST: 'Data Fetched Successfully',
    AUTH: {
      LOGIN_SUCCESS: 'Login Successful',
      INVALID_CREDENTIALS: 'Invalid email or password',
      UNAUTHORIZED: 'Unauthorized Access',
    },
    USER: {
      NOT_FOUND: 'User Not Found',
      EMAIL_ALREADY_IN_USE: 'Email address is already in use',
      USER_ID_TAKEN: 'User ID is already taken',
    },
    INVITATION: {
      SENT: 'Invitation Sent Successfully',
      NOT_FOUND: 'Invitation Not Found',
      EXPIRED: 'Invitation Has Expired',
      ALREADY_USED: 'Invitation Has Already Been Used',
      RESENT: 'Invitation Resent Successfully',
    },
    REGISTRATION: {
      COMPLETED: 'Registration Completed Successfully',
      PAYMENT_SUCCESS: 'Payment Processed Successfully',
    },
    HR: {
      CREATED: 'HR Account Created Successfully',
      UPDATED: 'HR Profile Updated Successfully',
      STATUS_UPDATED: 'HR Account Status Updated Successfully',
      NOT_FOUND: 'HR Staff Member Not Found',
      ALREADY_EXISTS: 'An HR staff member with this employee ID or email already exists',
    },
    HIRING_PIPELINE: {
      SAVED: 'Hiring pipeline saved successfully',
      STAGE_CREATED: 'Pipeline stage created successfully',
      STAGE_UPDATED: 'Pipeline stage updated successfully',
      STAGE_DELETED: 'Pipeline stage deleted successfully',
      REORDERED: 'Pipeline stages reordered successfully',
      STAGE_NOT_FOUND: 'Pipeline stage not found',
      STAGES_REQUIRED: 'At least one pipeline stage is required',
    },
    JOB: {
      CREATED: 'Job created successfully',
      UPDATED: 'Job updated successfully',
      DELETED: 'Job deleted successfully',
      NOT_FOUND: 'Job not found',
      CODE_EXISTS: 'A job with this code already exists',
      AI_GENERATED: 'Job content generated successfully',
      HIRING_COMPLETE: 'Hiring cycle marked complete — hired candidate added to caregiver roster',
      HIRING_ALREADY_COMPLETE: 'Hiring cycle is already complete for this job',
      HIRING_REOPENED: 'Hiring cycle reopened for this job',
      HIRING_COMPLETE_REQUIRES_HIRE: 'At least one candidate must be hired before completing the hiring cycle',
      HIRING_CYCLE_LOCKED: 'Reopen the hiring cycle before adding candidates or editing this job',
    },
    CANDIDATE: {
      APPLIED: 'Candidate added to job successfully',
      ALREADY_APPLIED: 'This candidate has already been added to this job',
      APPLICATION_NOT_FOUND: 'Application not found',
      INVALID_STAGE: 'Invalid pipeline stage for this job',
      STAGE_UPDATED: 'Candidate stage updated successfully',
      HIRED: 'Candidate marked as hired',
      CAREGIVER_TRANSFERRED: 'Hired candidate transferred to caregiver roster',
      HIRED_LOCKED: 'Reopen the hiring cycle before changing hired candidate status',
      HIRE_UNDONE: 'Candidate moved back to final hiring stage',
      REJECTED: 'Candidate rejected',
      NOT_FOUND: 'Candidate not found',
      NOT_FINAL_STAGE: 'Candidate must be at the final pipeline stage to complete hiring',
      ALREADY_HIRED: 'Candidate has already been hired',
      NOT_ACTIVE: 'Only active candidates can be moved',
      NOT_HIRED: 'Only hired candidates can be moved back to the final stage',
      NO_NEXT_STAGE: 'No next stage available',
      NO_PREVIOUS_STAGE: 'No previous stage available',
      JOB_HIRE_LIMIT: 'Only one candidate can be hired for this job',
      CAREGIVER_ACCOUNT_CONFLICT: 'Email is already used by a non-caregiver account',
    },
    CAREGIVER: {
      NOT_FOUND: 'Caregiver not found',
      PASSWORD_UPDATED: 'Caregiver password updated successfully',
    },
    CLIENT: {
      CREATED: 'Client created successfully',
      UPDATED: 'Client updated successfully',
      DELETED: 'Client deleted successfully',
      NOT_FOUND: 'Client not found',
      HAS_CARE_PLANS: 'Cannot delete client with existing care plans',
    },
    CARE_PLAN: {
      CREATED: 'Care plan created successfully',
      UPDATED: 'Care plan updated successfully',
      DELETED: 'Care plan deleted successfully',
      NOT_FOUND: 'Care plan not found',
      QUOTE_CREATED: 'Care plan quote generated successfully',
      QUOTE_ACCEPTED: 'Client onboarded and care plan activated',
      ALREADY_QUOTED: 'A quote already exists for this assessment',
      NOT_QUOTED: 'Generate a quote before accepting',
    },
    ASSESSMENT: {
      CREATED: 'Client assessment saved successfully',
      UPDATED: 'Client assessment updated successfully',
      DELETED: 'Client assessment deleted successfully',
      NOT_FOUND: 'Client assessment not found',
      ALREADY_ACCEPTED: 'This assessment has already been accepted',
    },
    INSURANCE_INTAKE: {
      CREATED: 'Insurance intake saved successfully',
      UPDATED: 'Insurance intake updated successfully',
      DELETED: 'Insurance intake deleted successfully',
      NOT_FOUND: 'Insurance intake not found',
    },
  },
};
