module.exports = {
  Auth: require('./admin/auth'),
  Invitation: require('./admin/invitation'),
  HrStaff: require('./agency/hrStaff'),
  HiringPipeline: require('./agency/hiringPipeline'),
  JobPost: require('./agency/jobPost'),
  CandidateApplication: require('./agency/candidateApplication'),
  CandidateForm: require('./agency/candidateForm'),
  InterviewFeedback: require('./agency/interviewFeedback'),
  Caregiver: require('./agency/caregiver'),
  Client: require('./agency/client'),
  ClientAssessment: require('./agency/clientAssessment'),
  CarePlan: require('./agency/carePlan'),
  InsuranceIntake: require('./agency/insuranceIntake'),
  EvvEnrollment: require('./agency/evvEnrollment'),
  VisitSchedule: require('./agency/visitSchedule'),
  EvvSettings: require('./agency/evvSettings'),
  ClientInvoice: require('./agency/clientInvoice'),
};
