module.exports = {
  AdminAuthController: require('./admin/AdminAuthController'),
  AgencyController: require('./admin/AgencyController'),
  SubscriptionPlanController: require('./admin/SubscriptionPlanController'),
  InvitationController: require('./admin/InvitationController'),
  RegistrationController: require('./registration/RegistrationController'),
  HrStaffController: require('./agency/HrStaffController'),
  HiringPipelineController: require('./agency/HiringPipelineController'),
  JobPostController: require('./agency/JobPostController'),
  CandidateApplicationController: require('./agency/CandidateApplicationController'),
  CandidateFormController: require('./agency/CandidateFormController'),
  InterviewFeedbackController: require('./agency/InterviewFeedbackController'),
  AgencyCaregiverController: require('./agency/AgencyCaregiverController'),
  ClientController: require('./agency/ClientController'),
  ClientAssessmentController: require('./agency/ClientAssessmentController'),
  CarePlanController: require('./agency/CarePlanController'),
  InsuranceIntakeController: require('./agency/InsuranceIntakeController'),
  EvvEnrollmentController: require('./agency/EvvEnrollmentController'),
  CaregiverController: require('./caregiver/CaregiverController'),
  CaregiverEvvEnrollmentController: require('./caregiver/EvvEnrollmentController'),
};
